version: "3"
services:
  gorse:
    image: zhenghaoz/gorse
    ports:
      - "8088:8088"
      - "8086:8086" # RPC port
    environment:
      - GORSE_CACHE_STORE=redis://redis:6379
      - GORSE_DATA_STORE=mysql://gorse:gorse_pass@mysql:3306/gorse
    command: -c /etc/gorse/config.toml # Use default or mounted config
    depends_on:
      - redis
      - mysql
    restart: always

  redis:
    image: redis
    ports:
      - "6379:6379"
    restart: always

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=gorse_pass
      - MYSQL_DATABASE=gorse
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
